import{S as d,i as c}from"./assets/vendor-5b791d57.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();function y(s){const r="https://pixabay.com/api/",o=new URLSearchParams({key:"43044638-81b288208bd41d7f3c4a2027f",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"}),n=`${r}?${o}`;return m(),fetch(n).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}function g(s){if(s.length==0)iziToast.error({message:"❌ Sorry, there are no images matching your search query. Please, try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}),a.innerHTML="";else{const o=s.map(({webformatURL:n,largeImageURL:e,tags:t,likes:i,views:p,comments:u,downloads:f})=>`<li class="gallery-item">
    <a class="gallery-link" href="${e}">
    <img class="gallery-image" src="${n}" alt="${t}" />
    </a>
    <div class="content-image">
    <p class="content-item">Likes<span class="info-item">${i}</span></p>
    <p class="content-item">Views<span class="info-item">${p}</span></p>
    <p class="content-item">Comments<span class="info-item">${u}</span></p>
    <p class="content-item">Downloads<span class="info-item">${f}</span></p>
    </div
    </li>`).join("");a.innerHTML=o}new d(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const a=document.querySelector(".gallery"),h=document.querySelector(".form"),l=document.querySelector(".conteiner-loader"),L=document.querySelector("input");l.style.display="none";const m=()=>{l.style.display="flex"},b=()=>{l.style.display="none"};h.addEventListener("submit",s=>{s.preventDefault();const r=L.value.trim();m(),r!==""&&(y(r).then(o=>g(o.hits)).catch(o=>{console.log(o),c.error({title:"Error",message:"❌ Sorry, there are no images matching your search query. Please, try again!",position:"topRight"})}),b()),r===""&&c.error({color:"yellow",message:" Please fill in the field for search",position:"topRight"}),a.innerHTML=""});
//# sourceMappingURL=commonHelpers.js.map
